# Generated by Django 3.0.7 on 2020-07-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_contact', '0003_auto_20200710_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_group',
            old_name='desc',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='contact_group',
            name='group',
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='first_contact.Contact_Group'),
            preserve_default=False,
        ),
    ]
