# Generated by Django 3.0.7 on 2020-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_contact', '0005_remove_contact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
